### ISSUE TITLE
Geosearch issues for some users

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/MRDATA#22]
Some folks are having issues getting the geosearch to work.
See the slack archive for details and some troubleshooting...

https://wim-usgs.slack.com/archives/C2R5JHEHF/p1490905062703415

**Comment by mitch-wim** [comment]
Closing this because as far as I can tell, I believe I fixed it. I think it had to do with HTTPS... the actual Geosearch API code had some references to http URLs instead of https - switching them to HTTPS seems to have removed all console errors, and doesn't seem to have had any consequences, so hopefully that fixes issues with the search (although I wasn't ever actually able to replicate issues people were having - so I can't be 100% sure)
